### ISSUE TITLE
access variable

### ISSUE THREAD

**Issue by kingM** [jgdavey/tabletastic#26]
table_for(@posts) do |t|
      @category = category.where(:id => @posts)
      t.column do |j|
        @category.id
      end
            t.column do |j|
        @category.name
      end
      .......
    end

not working pls help

**Comment by jgdavey** [comment]
There are a number of errors in the example above, any of which could be why it isn't working. For category, you probably mean the `Category` constant, rather than a local. Also, I don't think that you probably want to select all categories where the id is in an array of posts. 

With regard to tabletastic specifically, every call to `t.column` should be nested in a `t.data` block. That also could be the source of your woes.

That said, if you trying to include every post's category id and name as part of the table, The default behavior will probably get close to what you want:

``` erb
<%= table_for(@posts) do |t|
  t.data :category_id, :category
end %>

```
