### ISSUE TITLE
specify the html options of the header

### ISSUE THREAD

**Issue by towerhe** [jgdavey/tabletastic#7]
i wanna some columns of the table will be ignored when some one exports or prints the table. so i need to add a class to the head as it does to the cell. i hacked the head method in TableBuilder and add field.cell_html as the third parameter of content_tag.

**Comment by jgdavey** [comment]
I like what you did in your fork, but I'd also like to keep the options separate, because there are just as many cases where the <code>&lt;th></code> and <code>&lt;td></code> need to be different.

I've added the <code>:heading_html</code> option in this commit: jgdavey/tabletastic@1c808c5742af7258f505

**Comment by jgdavey** [comment]
This has been incorporated into the latest release, v0.2.0
